[project]
name = "1-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pytest>=8.4.2",
    "pre-commit>=4.0.0",
    "black>=24.8.0",
    "mypy>=1.11.0",
]
